import { createFileRoute } from "@tanstack/react-router";
import { CalendarDays, HandHeart, RefreshCcw } from "lucide-react";
import { EmptyState, InfoCard, PageHero, SectionTitle, SimpleForm } from "@/components/site";
import { Button } from "@/components/ui/button";
import { pageHead } from "@/lib/seo";
import comoAjudarHero from "@/assets/como-ajudar-hero.jpg";


export const Route=createFileRoute("/como-ajudar")({head:()=>pageHead("Como ajudar | Instituto Francisquinho","Conheça formas de apoiar o Instituto Francisquinho com doações, voluntariado, campanhas e eventos.","/como-ajudar"),component:HelpPage});
function HelpPage(){return <><PageHero eyebrow="Faça parte" title="Juntos, podemos ampliar o apoio às famílias" description="Existem diferentes maneiras de contribuir. Escolha a forma que combina com você e ajude a fortalecer nossas ações."/><section className="site-container section-space"><SectionTitle eyebrow="Contribua" title="Doações únicas e mensais" description="Os canais de pagamento serão publicados após a configuração e validação institucional."/><div className="mt-10 grid gap-5 md:grid-cols-2"><InfoCard icon={HandHeart} title="Doação única"><p>Uma contribuição pontual pode ajudar a fortalecer nossas ações.</p><Button type="button" variant="outline" className="mt-6" disabled>Link em preparação</Button></InfoCard><InfoCard icon={RefreshCcw} title="Doação mensal"><p>O apoio recorrente contribui para a continuidade dos projetos e ações do Instituto.</p><Button type="button" variant="outline" className="mt-6" disabled>Link em preparação</Button></InfoCard></div></section><section className="bg-surface-soft"><div className="site-container section-space grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><SectionTitle eyebrow="Voluntariado" title="Seu tempo e conhecimento podem ajudar" description="Conte um pouco sobre como gostaria de colaborar. A equipe poderá entrar em contato quando houver oportunidades compatíveis."/></div><div className="border border-border bg-background p-6 md:p-8"><SimpleForm kind="voluntariado"/></div></div></section><section className="site-container section-space"><SectionTitle eyebrow="Mobilização" title="Campanhas e eventos"/><div className="mt-8"><EmptyState title="Novidades em breve" description="Em breve, você poderá acompanhar nossas campanhas e eventos."/></div><div className="mt-8 flex items-center gap-3 text-sm text-muted-foreground"><CalendarDays className="text-accent-strong"/><span>Datas e detalhes serão publicados somente após confirmação.</span></div></section></>}