import { createFileRoute } from "@tanstack/react-router";
import { Accessibility, Activity, Apple, BookOpenCheck, Files, HeartHandshake, Home, MessageCircleHeart, MessagesSquare, Scale, Speech, Stethoscope, Users } from "lucide-react";
import { AlertBanner, ContactPanel, InfoCard, PageHero, SectionTitle } from "@/components/site";
import { pageHead } from "@/lib/seo";

export const Route = createFileRoute("/recebi-o-diagnostico")({
  head: () => pageHead("Diagnóstico, cuidados e tratamento | Instituto Francisquinho", "Orientações iniciais, cuidados e informações sobre tratamento para famílias após um diagnóstico ou suspeita de CLN2.", "/recebi-o-diagnostico"),
  component: DiagnosisPage,
});

const steps = ["Busque orientação médica especializada", "Organize exames e documentos", "Converse com a equipe de saúde sobre o acompanhamento", "Procure informações confiáveis", "Conheça seus direitos e possibilidades de apoio", "Busque uma rede de acolhimento para a família"];
const supports = [[Stethoscope,"Equipe médica","Converse sobre diagnóstico, exames e possibilidades de acompanhamento."],[HeartHandshake,"Equipe multidisciplinar","Busque orientações integradas de acordo com as necessidades e indicação clínica."],[MessagesSquare,"Instituto Francisquinho","Encontre acolhimento, informação acessível e canais de orientação."],[BookOpenCheck,"Serviços de saúde","Informe-se sobre os serviços e fluxos disponíveis em sua região."] ] as const;
const professionals = [[Activity,"Fisioterapia"],[Speech,"Fonoaudiologia"],[Apple,"Nutrição"],[Accessibility,"Terapia ocupacional"],[Users,"Outros profissionais"]] as const;

function DiagnosisPage() { return <>
  <PageHero eyebrow="Da orientação ao cuidado" title="Recebi um diagnóstico. Quais são os próximos passos?" description="Sabemos que receber a notícia de uma doença rara pode trazer muitas dúvidas. Esta página reúne primeiros passos, informações sobre cuidados e caminhos para buscar apoio." />
  <div className="site-container py-10"><AlertBanner title="Respire. Você não precisa entender tudo de uma vez."><p>Comece por um passo de cada vez. Guarde suas dúvidas e leve-as às pessoas que acompanham sua família.</p></AlertBanner></div>
  <section className="site-container section-space pt-8"><SectionTitle eyebrow="Um caminho possível" title="Primeiros passos" description="Cada família tem uma realidade diferente. Use esta sequência como apoio para organizar o começo da jornada."/><ol className="mt-10 grid gap-4 md:grid-cols-2">{steps.map((step,i)=><li key={step} className="grid grid-cols-[3rem_minmax(0,1fr)] items-start gap-4 border-b border-border py-5"><span className="grid size-12 place-items-center rounded-full bg-primary font-black text-primary-foreground">{i+1}</span><div><h3 className="pt-2 text-lg font-black text-primary">{step}</h3></div></li>)}</ol></section>
  <section className="bg-surface-soft"><div className="site-container section-space grid gap-10 lg:grid-cols-2"><div><SectionTitle eyebrow="Entenda com calma" title="O que é a CLN2?"/><p className="mt-5 leading-7 text-muted-foreground">A CLN2 é uma doença rara que afeta o sistema nervoso e pode provocar mudanças progressivas no desenvolvimento e nas habilidades da criança. O diagnóstico e o acompanhamento devem ser conduzidos por profissionais de saúde qualificados.</p><p className="mt-4 border-l-4 border-accent-strong pl-4 text-sm leading-6 text-muted-foreground">Este conteúdo é introdutório e não substitui avaliação, diagnóstico ou orientação médica.</p></div><div className="grid grid-cols-2 gap-4"><InfoCard icon={Files} title="Organize"><p>Reúna exames, laudos, receitas e contatos importantes.</p></InfoCard><InfoCard icon={Scale} title="Informe-se"><p>Anote dúvidas e procure fontes oficiais e responsáveis.</p></InfoCard></div></div></section>
  <section className="site-container section-space"><SectionTitle eyebrow="Rede de apoio" title="Onde buscar ajuda?"/><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{supports.map(([icon,title,text])=><InfoCard key={title} icon={icon} title={title}><p>{text}</p></InfoCard>)}</div></section>
  <section className="bg-surface-soft"><div className="site-container section-space"><SectionTitle eyebrow="Tratamento" title="Infusão de Cerliponase Alfa"/><div className="mt-8 grid gap-8 lg:grid-cols-[1.3fr_.7fr]"><div className="prose-copy"><p>A Cerliponase Alfa é uma terapia relacionada ao cuidado de pessoas com CLN2. A indicação, o acesso e todas as decisões sobre o tratamento dependem da avaliação da equipe médica responsável.</p><p>O acompanhamento deve considerar a situação de cada pessoa, com orientações dadas pelos profissionais que conhecem seu histórico e suas necessidades.</p></div><AlertBanner title="Decisão compartilhada"><p>Não apresentamos doses, frequência ou protocolos. Converse sempre com a equipe médica responsável.</p></AlertBanner></div></div></section>
  <section className="site-container section-space"><SectionTitle eyebrow="Acompanhamento" title="Equipe multidisciplinar" description="O cuidado pode envolver diferentes áreas, conforme avaliação clínica e necessidades de cada pessoa."/><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-5">{professionals.map(([icon,title])=><InfoCard key={title} icon={icon} title={title}><p>Acompanhamento quando indicado pela equipe responsável.</p></InfoCard>)}</div><p className="mt-6 text-sm text-muted-foreground">A lista é informativa e não afirma que o Instituto possui estes profissionais.</p></section>
  <section className="bg-surface-soft"><div className="site-container section-space grid gap-10 lg:grid-cols-2"><div><SectionTitle eyebrow="Dia a dia" title="Rotina em casa e adaptações"/><ul className="mt-6 space-y-4 text-muted-foreground"><li className="flex gap-3"><Home className="shrink-0 text-accent-strong" aria-hidden="true"/>Organize rotinas possíveis e revise a segurança dos ambientes.</li><li className="flex gap-3"><Accessibility className="shrink-0 text-accent-strong" aria-hidden="true"/>Converse com profissionais sobre acessibilidade e adaptações.</li><li className="flex gap-3"><MessageCircleHeart className="shrink-0 text-accent-strong" aria-hidden="true"/>Valorize formas de comunicação, vínculo e participação.</li></ul></div><div><SectionTitle eyebrow="Cuidar de quem cuida" title="Apoio à família"/><p className="mt-6 leading-7 text-muted-foreground">Compartilhar responsabilidades, organizar informações e manter diálogo com a equipe de saúde pode tornar a rotina mais segura. A família e o cuidador também precisam de escuta, pausas e uma rede de apoio.</p><div className="mt-6"><InfoCard icon={HeartHandshake} title="Você também importa"><p>Buscar acolhimento emocional é parte do cuidado, não sinal de fraqueza.</p></InfoCard></div></div></div></section>
  <ContactPanel />
</>; }