/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComoAjudarRouteImport } from './routes/como-ajudar'
import { Route as CuidadosETratamentoRouteImport } from './routes/cuidados-e-tratamento'
import { Route as DireitosEOrientacaoRouteImport } from './routes/direitos-e-orientacao'
import { Route as OutrasDoencasRarasRouteImport } from './routes/outras-doencas-raras'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as RecebiODiagnosticoRouteImport } from './routes/recebi-o-diagnostico'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoAjudarRoute = ComoAjudarRouteImport.update({
  id: '/como-ajudar',
  path: '/como-ajudar',
  getParentRoute: () => rootRouteImport,
} as any)
const CuidadosETratamentoRoute = CuidadosETratamentoRouteImport.update({
  id: '/cuidados-e-tratamento',
  path: '/cuidados-e-tratamento',
  getParentRoute: () => rootRouteImport,
} as any)
const DireitosEOrientacaoRoute = DireitosEOrientacaoRouteImport.update({
  id: '/direitos-e-orientacao',
  path: '/direitos-e-orientacao',
  getParentRoute: () => rootRouteImport,
} as any)
const OutrasDoencasRarasRoute = OutrasDoencasRarasRouteImport.update({
  id: '/outras-doencas-raras',
  path: '/outras-doencas-raras',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const RecebiODiagnosticoRoute = RecebiODiagnosticoRouteImport.update({
  id: '/recebi-o-diagnostico',
  path: '/recebi-o-diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/como-ajudar': typeof ComoAjudarRoute
  '/cuidados-e-tratamento': typeof CuidadosETratamentoRoute
  '/direitos-e-orientacao': typeof DireitosEOrientacaoRoute
  '/outras-doencas-raras': typeof OutrasDoencasRarasRoute
  '/quem-somos': typeof QuemSomosRoute
  '/recebi-o-diagnostico': typeof RecebiODiagnosticoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-ajudar': typeof ComoAjudarRoute
  '/cuidados-e-tratamento': typeof CuidadosETratamentoRoute
  '/direitos-e-orientacao': typeof DireitosEOrientacaoRoute
  '/outras-doencas-raras': typeof OutrasDoencasRarasRoute
  '/quem-somos': typeof QuemSomosRoute
  '/recebi-o-diagnostico': typeof RecebiODiagnosticoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/como-ajudar': typeof ComoAjudarRoute
  '/cuidados-e-tratamento': typeof CuidadosETratamentoRoute
  '/direitos-e-orientacao': typeof DireitosEOrientacaoRoute
  '/outras-doencas-raras': typeof OutrasDoencasRarasRoute
  '/quem-somos': typeof QuemSomosRoute
  '/recebi-o-diagnostico': typeof RecebiODiagnosticoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/como-ajudar'
    | '/cuidados-e-tratamento'
    | '/direitos-e-orientacao'
    | '/outras-doencas-raras'
    | '/quem-somos'
    | '/recebi-o-diagnostico'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/como-ajudar'
    | '/cuidados-e-tratamento'
    | '/direitos-e-orientacao'
    | '/outras-doencas-raras'
    | '/quem-somos'
    | '/recebi-o-diagnostico'
  id:
    | '__root__'
    | '/'
    | '/como-ajudar'
    | '/cuidados-e-tratamento'
    | '/direitos-e-orientacao'
    | '/outras-doencas-raras'
    | '/quem-somos'
    | '/recebi-o-diagnostico'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComoAjudarRoute: typeof ComoAjudarRoute
  CuidadosETratamentoRoute: typeof CuidadosETratamentoRoute
  DireitosEOrientacaoRoute: typeof DireitosEOrientacaoRoute
  OutrasDoencasRarasRoute: typeof OutrasDoencasRarasRoute
  QuemSomosRoute: typeof QuemSomosRoute
  RecebiODiagnosticoRoute: typeof RecebiODiagnosticoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-ajudar': {
      id: '/como-ajudar'
      path: '/como-ajudar'
      fullPath: '/como-ajudar'
      preLoaderRoute: typeof ComoAjudarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuidados-e-tratamento': {
      id: '/cuidados-e-tratamento'
      path: '/cuidados-e-tratamento'
      fullPath: '/cuidados-e-tratamento'
      preLoaderRoute: typeof CuidadosETratamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direitos-e-orientacao': {
      id: '/direitos-e-orientacao'
      path: '/direitos-e-orientacao'
      fullPath: '/direitos-e-orientacao'
      preLoaderRoute: typeof DireitosEOrientacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outras-doencas-raras': {
      id: '/outras-doencas-raras'
      path: '/outras-doencas-raras'
      fullPath: '/outras-doencas-raras'
      preLoaderRoute: typeof OutrasDoencasRarasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recebi-o-diagnostico': {
      id: '/recebi-o-diagnostico'
      path: '/recebi-o-diagnostico'
      fullPath: '/recebi-o-diagnostico'
      preLoaderRoute: typeof RecebiODiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComoAjudarRoute: ComoAjudarRoute,
  CuidadosETratamentoRoute: CuidadosETratamentoRoute,
  DireitosEOrientacaoRoute: DireitosEOrientacaoRoute,
  OutrasDoencasRarasRoute: OutrasDoencasRarasRoute,
  QuemSomosRoute: QuemSomosRoute,
  RecebiODiagnosticoRoute: RecebiODiagnosticoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
